### ISSUE TITLE
Discord invite invalid

### ISSUE THREAD

**Issue by koslX** [darellanodev/jetpack-game#14]
When trying to join using [link from README.md](https://discord.gg/uRMVBRNd ) i get a message "the invite is invalid or has expired. 
![image](https://github.com/user-attachments/assets/f588fd71-0672-4f84-b7de-d61704176b2f)

**Comment by darellanodev** [comment]
Thank you for detecting the problem. I have now generated another link and selected the option to prevent the link from expiring. I have also updated the README.md file.

I forgot to include the reference to this issue in the commit, so I'm closing it manually.
